"""initial_schema

Revision ID: 0001
Revises:
Create Date: 2026-09-27 17:54:30.387074

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("disabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "workspaces",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("content_retention_days", sa.Integer(), server_default="7", nullable=False),
        sa.Column("activity_retention_days", sa.Integer(), server_default="90", nullable=False),
        sa.CheckConstraint("activity_retention_days > 0", name="positive_activity_retention"),
        sa.CheckConstraint("content_retention_days > 0", name="positive_content_retention"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("event_code", sa.String(length=40), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_events_workspace_time",
        "audit_events",
        ["workspace_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "memberships",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("role IN ('member', 'administrator')", name="valid_role"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("workspace_id", "user_id"),
    )
    op.create_table(
        "presets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("categories", sa.String(length=300), nullable=False),
        sa.Column("phone_region", sa.String(length=2), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("version > 0", name="positive_version"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "name", name="uq_presets_workspace_name"),
    )
    op.create_table(
        "recovery_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(), nullable=False),
        sa.Column("csrf_hash", sa.LargeBinary(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index("ix_sessions_user_expiry", "sessions", ["user_id", "expires_at"], unique=False)
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("title_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("title_key_id", sa.String(length=80), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="draft", nullable=False),
        sa.Column("current_revision_id", sa.UUID(), nullable=True),
        sa.Column("decision_version", sa.Integer(), server_default="0", nullable=False),
        sa.Column("settings_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "category_settings", sa.String(length=300), server_default="email,phone", nullable=False
        ),
        sa.Column("phone_region", sa.String(length=2), server_default="US", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('draft', 'scanning', 'needs_review', 'ready', 'exported', 'failed', 'expired', 'deleted')",
            name="valid_status",
        ),
        sa.CheckConstraint(
            "(title_ciphertext IS NULL AND title_key_id IS NULL) OR (title_ciphertext IS NOT NULL AND title_key_id IS NOT NULL)",
            name="title_encryption_pair",
        ),
        sa.CheckConstraint("decision_version >= 0", name="nonnegative_decision_version"),
        sa.CheckConstraint("expires_at > created_at", name="expiry_after_creation"),
        sa.CheckConstraint("settings_version >= 1", name="positive_settings_version"),
        sa.ForeignKeyConstraint(
            ["id", "current_revision_id"],
            ["source_revisions.document_id", "source_revisions.id"],
            name="fk_documents_current_revision",
            deferrable=True,
            initially="DEFERRED",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "owner_id"],
            ["memberships.workspace_id", "memberships.user_id"],
            name="fk_documents_owner_membership",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_documents_owner_created", "documents", ["owner_id", "created_at"], unique=False
    )
    op.create_index("ix_documents_expiry", "documents", ["expires_at"], unique=False)
    op.create_table(
        "label_counters",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("category", sa.String(length=24), nullable=False),
        sa.Column("next_number", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("next_number > 0", name="positive_next_label_number"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("document_id", "category"),
    )
    op.create_table(
        "source_revisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("source_ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("source_key_id", sa.String(length=80), nullable=False),
        sa.Column("utf8_bytes", sa.Integer(), nullable=False),
        sa.Column("code_points", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("code_points > 0 AND code_points <= 100000", name="valid_source_points"),
        sa.CheckConstraint("revision_number > 0", name="positive_revision_number"),
        sa.CheckConstraint("utf8_bytes > 0 AND utf8_bytes <= 1048576", name="valid_source_bytes"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "id", name="uq_source_revisions_document_id"),
        sa.UniqueConstraint("document_id", "revision_number", name="uq_source_revisions_number"),
    )
    op.create_table(
        "entity_groups",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("source_revision_id", sa.UUID(), nullable=False),
        sa.Column("category", sa.String(length=24), nullable=False),
        sa.Column("label", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('person', 'organization', 'address', 'identifier', 'custom', 'email', 'phone')",
            name="valid_category",
        ),
        sa.ForeignKeyConstraint(
            ["document_id", "source_revision_id"],
            ["source_revisions.document_id", "source_revisions.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "id", name="uq_entity_groups_document_id"),
        sa.UniqueConstraint("document_id", "label", name="uq_entity_groups_document_label"),
        sa.UniqueConstraint(
            "document_id", "source_revision_id", "id", name="uq_entity_groups_revision_id"
        ),
    )
    op.create_table(
        "review_completions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("source_revision_id", sa.UUID(), nullable=False),
        sa.Column("decision_version", sa.Integer(), nullable=False),
        sa.Column("settings_version", sa.Integer(), nullable=False),
        sa.Column("confirmed_by", sa.UUID(), nullable=False),
        sa.Column(
            "confirmed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("decision_version >= 0", name="nonnegative_decision_version"),
        sa.CheckConstraint("settings_version >= 1", name="positive_settings_version"),
        sa.ForeignKeyConstraint(["confirmed_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["document_id", "source_revision_id"],
            ["source_revisions.document_id", "source_revisions.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "id", name="uq_review_completions_document_id"),
        sa.UniqueConstraint(
            "document_id",
            "source_revision_id",
            "decision_version",
            "settings_version",
            name="uq_review_completion_version",
        ),
    )
    op.create_table(
        "export_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("completion_id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=False),
        sa.Column("format", sa.String(length=12), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("format IN ('copy', 'txt')", name="valid_format"),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["document_id", "completion_id"],
            ["review_completions.document_id", "review_completions.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "findings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("source_revision_id", sa.UUID(), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=True),
        sa.Column("category", sa.String(length=24), nullable=False),
        sa.Column("origin", sa.String(length=16), nullable=False),
        sa.Column("rule_id", sa.String(length=80), nullable=True),
        sa.Column("rule_version", sa.String(length=30), nullable=True),
        sa.Column("start_offset", sa.Integer(), nullable=False),
        sa.Column("end_offset", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("removed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "category IN ('person', 'organization', 'address', 'identifier', 'custom', 'email', 'phone')",
            name="valid_category",
        ),
        sa.CheckConstraint("origin IN ('manual', 'automatic')", name="valid_origin"),
        sa.CheckConstraint("start_offset >= 0 AND end_offset > start_offset", name="valid_span"),
        sa.ForeignKeyConstraint(
            ["document_id", "source_revision_id", "group_id"],
            ["entity_groups.document_id", "entity_groups.source_revision_id", "entity_groups.id"],
            deferrable=True,
            initially="DEFERRED",
        ),
        sa.ForeignKeyConstraint(
            ["document_id", "source_revision_id"],
            ["source_revisions.document_id", "source_revisions.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "id", name="uq_findings_document_id"),
    )
    op.create_index(
        "ix_findings_revision", "findings", ["source_revision_id", "start_offset"], unique=False
    )
    op.create_table(
        "decisions",
        sa.Column("finding_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.String(length=12), nullable=False),
        sa.Column("keep_reason", sa.String(length=32), nullable=True),
        sa.Column("decided_by", sa.UUID(), nullable=False),
        sa.Column("decision_version", sa.Integer(), nullable=False),
        sa.Column(
            "decided_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(action = 'keep' AND keep_reason IS NOT NULL) OR (action <> 'keep' AND keep_reason IS NULL)",
            name="keep_requires_reason",
        ),
        sa.CheckConstraint("action IN ('label', 'redact', 'keep')", name="valid_action"),
        sa.CheckConstraint("decision_version > 0", name="positive_decision_version"),
        sa.ForeignKeyConstraint(["decided_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["finding_id"], ["findings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("finding_id"),
    )
    op.create_foreign_key(
        "fk_documents_current_revision",
        "documents",
        "source_revisions",
        ["id", "current_revision_id"],
        ["document_id", "id"],
        deferrable=True,
        initially="DEFERRED",
        use_alter=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_documents_current_revision", "documents", type_="foreignkey")
    op.drop_table("decisions")
    op.drop_table("findings")
    op.drop_table("export_events")
    op.drop_table("review_completions")
    op.drop_table("entity_groups")
    op.drop_table("source_revisions")
    op.drop_table("label_counters")
    op.drop_table("documents")
    op.drop_table("sessions")
    op.drop_table("recovery_tokens")
    op.drop_table("presets")
    op.drop_table("memberships")
    op.drop_table("audit_events")
    op.drop_table("workspaces")
    op.drop_table("users")
    # ### end Alembic commands ###
