import { useEffect, useRef } from 'react'
import { ArrowLeft, FileText, ShieldCheck } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Brand } from '../ui/Brand'
import { AppCredit } from '../ui/AppCredit'
import './legal.css'

const support = <a href="mailto:support@openanonymi.com">support@openanonymi.com</a>
const source = 'https://github.com/ShianMike/OpenAnonymi'

const terms = [
  { id: 'service', title: 'Using OpenAnonymi', content: <p>OpenAnonymi is operated by Shian Meris, based in the Philippines. These terms cover the hosted service at openanonymi.com. By creating an account or using the hosted service, you agree to these terms. Other installations are run by their own operators and may have different terms and privacy practices.</p> },
  { id: 'account', title: 'Your account and workspace', content: <><p>Use an email address you control, protect your password and recovery codes, and tell us if you suspect unauthorized access. You are responsible for activity you authorize through your account.</p><p>Workspace roles determine access. Only invite or assign people who are authorized to see the relevant content. Review owners remain responsible for source edits, confirmation, and sharing. Teammate approval applies to the reviewed version, rather than every future edit.</p></> },
  { id: 'content', title: 'Your content stays yours', content: <><p>You retain your rights to the content you upload. You give the service permission to store, extract, process, and display it as needed to provide the review and collaboration you request. This permission does not transfer ownership of your documents to OpenAnonymi.</p><p>Only upload content you have the right and an appropriate legal basis to process. Take particular care with information about other people, confidential documents, and sensitive information. Do not use the service for unlawful activity, attempt to access another person’s account, or disrupt the service.</p></> },
  { id: 'review', title: 'Review before sharing', content: <><p>Detection and OCR can miss or misclassify details. Removing names alone may not prevent someone from being identified through context. OpenAnonymi does not guarantee anonymity, legal compliance, or the accuracy of suggestions.</p><p>Check imported text, decide each finding, add missed details, and read the complete output before confirming or exporting. You are responsible for the final content and who receives it.</p></> },
  { id: 'availability', title: 'Availability and saved content', content: <><p>The service is provided as available. Features can change, and maintenance or failures can interrupt access. We do not promise uninterrupted service or recovery of every saved draft.</p><p>Saved content expires according to its retention settings. Keep your own copy of material you need. Exported files are under your control; deleting a review here does not delete copies already downloaded or shared. We may restrict access to protect users or respond to misuse or legal requirements.</p></> },
  { id: 'license', title: 'Service terms and the software license', content: <p>The software is published under the <a href={`${source}/blob/main/LICENSE`}>GNU Affero General Public License v3.0 or later</a>. That license and the <a href={`${source}/blob/main/NOTICE`}>copyright and attribution notices</a> govern use and redistribution of the code. These service terms do not replace or restrict the rights granted by that license.</p> },
  { id: 'terms-contact', title: 'Questions and changes', content: <><p>Contact {support} about the service, your account, or these terms. Do not send passwords, verification codes, or full private documents. We may need to confirm account ownership before acting on a request.</p><p>Updates will be published here with a revised date. Any rights that cannot be excluded under applicable law remain in place. Read the <Link to="/privacy">Privacy Notice</Link> for how the hosted service handles information.</p></> },
]

const privacy = [
  { id: 'operator', title: 'Who this notice covers', content: <p>This notice covers OpenAnonymi’s hosted service at openanonymi.com, operated by Shian Meris, based in the Philippines. For account and data requests, contact {support}. If you use a self-hosted copy, ask its operator about their storage, hosting, and privacy practices.</p> },
  { id: 'information', title: 'What information is processed', content: <ul><li><strong>Account and access:</strong> your email address, password hash, email-verification status, authentication and recovery records, workspace memberships, and roles.</li><li><strong>Review content:</strong> text and files you import, extracted text, findings, decisions, comments, review history, and protected working drafts.</li><li><strong>Activity:</strong> actions taken on reviews, assignments, approvals, notifications, timestamps, and relevant account and document identifiers.</li><li><strong>Network and security:</strong> hosting providers process request information such as IP addresses, browser information, and timing to deliver and protect the service. The app uses limited security records to prevent abusive requests.</li></ul> },
  { id: 'purpose', title: 'Why the service uses it', content: <><p>Account and review information is processed to provide the service you request under the <Link to="/terms">Terms of Service</Link>: signing in, importing content, producing suggestions, saving your decisions, and collaborating with authorized teammates. Security information helps protect accounts and keep the service available.</p><p>Verification, recovery, and security emails support account access. Optional notification emails follow your account preference and can be turned off in Settings. You are responsible for the authority and legal basis to process other people’s information in your documents.</p></> },
  { id: 'access', title: 'Who can access it', content: <><p>Review content is made available according to ownership, reviewer assignments, and workspace permissions. Share only with people who should have access. Authorized service operators may need access for support, maintenance, security, or a legal requirement.</p><p>The hosted service uses Heroku for application hosting, Supabase for its database, Cloudflare for delivery and security, and iCloud Mail for service and support email. These providers can process information needed for their role, including request metadata and traffic statistics at the network edge. Processing can occur outside your country.</p><p>Detection and OCR run on the service infrastructure. Uploaded document content is not sent to an external AI service for detection.</p></> },
  { id: 'protection', title: 'How information is protected', content: <><p>The service uses HTTPS, access checks, protected session cookies, password hashing, and encryption for stored document content and working drafts. Encryption keys are controlled by the service operator. This is not end-to-end encryption: the server can decrypt content to process your review.</p><p>No system can promise complete security. Detection is a review aid and does not guarantee that an exported document is anonymous. Report a suspected vulnerability through the project’s <a href={`${source}/security/advisories/new`}>private security reporting channel</a>; avoid posting sensitive details in public issues.</p></> },
  { id: 'retention', title: 'How long information is kept', content: <><p>Workspace administrators choose defaults of 1–30 days for new review content and 1–365 days for activity records. Check the expiry shown on each review; permitted retention changes can alter it. Protected working drafts also expire, and notification records are scheduled for cleanup after 30 days.</p><p>Expired or deleted reviews become inaccessible before stored content is physically removed by scheduled cleanup. Security, session, and temporary authentication records have their own expiry and cleanup rules. Account and membership information remains while the account and workspace access are maintained; contact support about closing an account.</p><p>Automatic database backups and point-in-time recovery are not enabled on the current hosting plan. Manual migration or recovery copies are managed separately from live-data cleanup and may retain earlier data. An automatic deletion deadline for those copies is not currently configured; contact {support} about removal from retained copies. Downloaded files, emailed notices, and copies held by recipients are not removed by deleting a review.</p></> },
  { id: 'device', title: 'Cookies and your device', content: <><p>Necessary cookies support sign-in and request protection. The browser stores display preferences, workspace selection, and review-position metadata so you can return to your work. Working-draft recovery is saved to the protected service, rather than storing raw document text in browser local storage.</p><p>Document text is present in browser memory while you view or edit it. Downloads and any copies you save stay on your device until you remove them. The landing-page demo uses fictional examples and does not save a review to the service. There are no advertising SDKs bundled in the app.</p></> },
  { id: 'rights', title: 'Your choices and requests', content: <><p>You can review account details, turn optional notification emails off, and use the deletion and retention controls available to your role. Contact {support} to request access, correction, deletion, or restriction of your information, or to raise a privacy concern. Rights and any exceptions depend on applicable law.</p><p>Start with a brief description of your request. Do not email passwords, one-time codes, or private document contents. We may need to verify your identity through an appropriate private process before disclosing data or changing access.</p><p>You can also contact the relevant privacy regulator; in the Philippines, see the <a href="https://privacy.gov.ph/data-subject-rights/">National Privacy Commission’s guidance on your rights</a>. Changes to this notice will appear here with a revised date.</p></> },
]

export function LegalPage({ notice }: { notice: 'terms' | 'privacy' }) {
  const isPrivacy = notice === 'privacy'
  const title = isPrivacy ? 'Privacy Notice' : 'Terms of Service'
  const sections = isPrivacy ? privacy : terms
  const heading = useRef<HTMLHeadingElement>(null)
  useEffect(() => {
    const previousTitle = document.title
    document.title = `${title} — OpenAnonymi`
    heading.current?.focus()
    return () => { document.title = previousTitle }
  }, [title])
  const Icon = isPrivacy ? ShieldCheck : FileText
  return <div className="legal-page">
    <a className="skip-link" href="#main-content">Skip to content</a>
    <header className="legal-masthead"><Link to="/welcome" aria-label="OpenAnonymi home"><Brand /></Link><Link to="/welcome"><ArrowLeft size={16} aria-hidden="true" /> Back to home</Link></header>
    <main id="main-content" className="legal-main">
      <nav className="legal-tabs" aria-label="Service notices"><Link to="/terms" aria-current={!isPrivacy ? 'page' : undefined}>Terms of Service</Link><Link to="/privacy" aria-current={isPrivacy ? 'page' : undefined}>Privacy Notice</Link></nav>
      <div className="legal-heading"><Icon size={26} aria-hidden="true" /><p>OpenAnonymi · Service information</p><h1 ref={heading} tabIndex={-1}>{title}</h1><p>{isPrivacy ? 'What is processed, who can access it, and the choices you have.' : 'What to expect from the service, and what stays in your hands.'}</p><small>Last updated <time dateTime="2026-10-09">9 October 2026</time></small></div>
      <div className="legal-layout">
        <nav className="legal-contents" aria-label="On this page"><strong>On this page</strong>{sections.map(({ id, title: sectionTitle }) => <a key={id} href={`#${id}`}>{sectionTitle}</a>)}</nav>
        <article>{sections.map(({ id, title: sectionTitle, content }) => <section key={id} id={id} aria-labelledby={`${id}-title`}><h2 id={`${id}-title`}>{sectionTitle}</h2>{content}</section>)}<div className="legal-contact"><ShieldCheck size={20} aria-hidden="true" /><div><strong>Need a hand?</strong><p>Account, support, and privacy requests: {support}</p></div></div></article>
      </div>
    </main>
    <footer className="legal-footer"><AppCredit /></footer>
  </div>
}
